### ISSUE TITLE
xsac_ui5_fesv5 not recognized in latest version of HANA Cockpit

### ISSUE THREAD

**Issue by dmcardlenl** [girid333/hckptoncont#1]
Hi,

FYI: I got this error in the build phase:

Configuration error (batch mode):
  Value "xsac_ui5_fesv5" is invalid. Please use one of: all, none, xsac_cockpit, xsac_hrtt, xsac_portal_serv, xsac_xsa_cockpit

using latest HAN Cockpit 2.0 (SAPHANACOCKPIT14_5).

Regards.

**Comment by girid333** [comment]
Thanks, Updated the components to install parameter. So the invalid option error message for xsac_ui5_fesv5 component will not appear.
