### ISSUE TITLE
Docker file needs modification when running in podman

### ISSUE THREAD

**Issue by dmcardlenl** [girid333/hckptoncont#3]
Hi,

I tried to build this on RHEL 8.4 and podman is the default instead of docker. 

I got this error, I'll post more details when I have it resolved.

    Installation of archive file '[/tmp/sapdownloads/COCKPIT2_APP/sap-xsac-cockpit-2.14.6.zip]' finished successfully.
SAP HANA Cockpit System installed

Launch SAP HANA cockpit by opening https://hckptn01:51026
Launch SAP HANA cockpit manager by opening https://hckptn01:51028

Log file written to '/var/tmp/hdb_H4C_hdblcm_install_2022-03-17_09.44.18/hdblcm.log' on host 'afa52665b6e4'.
su: cannot open session: Permission denied
su: cannot open session: Permission denied
Error: error building at STEP "RUN echo "$(hostname -I | awk '{print $1}')     hckptn01" >> /etc/hosts | ./hdblcm.sh --action=install --configfile=/tmp/sapdownloads/h4c_config -b; su - h4cadm -c "HDB stop"; rm -rf /hana/shared/H4C/xs/app_working/stager; su - h4cadm -c "mkdir /hana/shared/H4C/xs/app_working/stager"": error while running runtime: exit status 1

**Comment by girid333** [comment]
Hi,

Thanks for writing your feedback, this repository is specifically written for docker based installation and not designed for podman.
As per your suggestion will create one new repository for podman separately.
